Controllers/AllowancesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PAYROL_SYSTEM.Interfaces;
using PAYROL_SYSTEM.Models;

namespace PAYROL_SYSTEM.Controllers
{
    public class AllowancesController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public AllowancesController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }



        [HttpPost]
        public async Task<IActionResult> AddAllowanceTransaction(AllowancePayment_Transactions allowance)
        {
            //  return Json(allowance);
            if (allowance != null)
            {
                await _unitOfWork.allowancePayment_Transactions.AddNew(allowance);
                _unitOfWork.save();
                TempData["successs"] = $"{allowance.strAmount} was added successfully into the system";
            }
            else
            {
                TempData["Err"] = "Something went wrong";
            }
            return Redirect("~/Allowances/Index");
        }



        [HttpPost]
        public async Task<IActionResult> EditAllowanceTransactions(AllowancePayment_Transactions allowance, string Employeename)
        {
            // return Json(allowance);
            if (allowance != null)
            {
                // return Json(overTime);
                await _unitOfWork.allowancePayment_Transactions.Update(allowance);
                _unitOfWork.save();
                TempData["successs"] = $"Allowance amount of {allowance.strAmount} for {Employeename}  was Updated successfully";
            }
            else
            {
                TempData["Err"] = "Something went wrong";
            }

            return Redirect("~/Allowances/Index");
        }


        //
        [HttpPost]
        public async Task<IActionResult> RemoveAllowanceTransaction(string id, string Employeename)
        {

         
            //   return Json(employees);
            if (id != null)
            {
                AllowancePayment_Transactions e = await _unitOfWork.allowancePayment_Transactions.GetById(id);
                if (e != null)
                {
                    await _unitOfWork.allowancePayment_Transactions.Remove(e);
                    _unitOfWork.save();
                    TempData["Err"] = $"Allowance amount of {e.strAmount} for {Employeename}  was Removed";
                }
                else
                {
                    TempData["Err"] = "Something went wrong";
                }
            }
            else
            {
                TempData["Err"] = "Something went wrong";
            }
            return Redirect("~/Allowances/Index");
        }


    }
}

Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PAYROL_SYSTEM.Interfaces;
using PAYROL_SYSTEM.Models;

namespace PAYROL_SYSTEM.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public EmployeesController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }


        public async Task<IActionResult> Index()
        {
            return View();
        }


        public async Task<IActionResult> OverTime()
        {
            return View();
        }


        public async Task<IActionResult> Commission()
        {
            return View();
        }



        public async Task<IActionResult> CreateNewEmployee()
        {
            return View();
        }



        public async Task<IActionResult> EditEmployee(string id)
        {
            if (id != null)
            {
                Employees e = await _unitOfWork.employeeRepo.GetById(id);
                if (e != null)
                {
                    return View(e);
                }
                else
                {
                    TempData["Err"] = "Something went wrong";
                    return Redirect("~/Employees/Index");
                }
            }
            TempData["Err"] = "Something went wrong";
            return Redirect("~/Employees/Index");
        }


        [HttpPost]
        public async Task<IActionResult> AddOverTime(OverTime overTime)
        {
            //return Json(employees);
            if (overTime != null)
            {
                await _unitOfWork.overTimeRepo.AddNew(overTime);
                _unitOfWork.save();
                TempData["successs"] = $"{overTime.strAmount} was added successfully into the system";
            }
            else
            {
                TempData["Err"] = "Something went wrong";
            }
            return Redirect("~/Employees/OverTime");
        }


        [HttpPost]
        public async Task<IActionResult> AddCommission(Commission commission)
        {
            //return Json(employees);
            if (commission != null)
            {
                await _unitOfWork.Icommissionrepo.AddNew(commission);
                _unitOfWork.save();
                TempData["successs"] = $"{commission.strAmount} was added successfully into the system";
            }
            else
            {
                TempData["Err"] = "Something went wrong";
            }
            return Redirect("~/Employees/Commission");
        }



        [HttpPost]
        public async Task<IActionResult> UpdateOverTime(OverTime overTime, string Employeename)
        {
            if (overTime != null)
            {
                // return Json(overTime);
                await _unitOfWork.overTimeRepo.Update(overTime);
                _unitOfWork.save();
                TempData["successs"] = $"Overtime amount of {overTime.strAmount} for {Employeename}  was Updated successfully";
            }
            else
            {
                TempData["Err"] = "Something went wrong";
            }
            return Redirect("~/Employees/OverTime");
        }




        [HttpPost]
        public async Task<IActionResult> UpdateCommission(Commission commission, string Employeename)
        {
            if (commission != null)
            {
                // return Json(overTime);
                await _unitOfWork.Icommissionrepo.Update(commission);
                _unitOfWork.save();
                TempData["successs"] = $"Commission amount of {commission.strAmount} for {Employeename}  was Updated successfully";
            }
            else
            {
                TempData["Err"] = "Something went wrong";
            }
            return Redirect("~/Employees/Commission");
        }


        [HttpPost]
        public async Task<IActionResult> CreateNewEmployee(Employees employees, CheckedAllowanceType checkedAllowanceType)
        {
            if (employees != null)
            {
                await _unitOfWork.employeeRepo.AddNew(employees);
                foreach (var data in checkedAllowanceType.checkedAllowances.Where(k => k.strIsChecked == true))
                {
                    Allowances allowances = new Allowances();
                    allowances.strId = Guid.NewGuid().ToString();
                    allowances.strUserId = employees.strId;
                    allowances.strAllowanceId = data.strAllowancetypeId;
                    await _unitOfWork.allowancesRepo.AddNew(allowances);
                }
                _unitOfWork.save();
                TempData["successs"] = $"{employees.strFullName} was added successfully into the system";
            }
            else
            {
                TempData["Err"] = "Something went wrong";
            }
            return Redirect("~/Employees/Index");
        }




        [HttpPost]
        public async Task<IActionResult> EditEmployee(Employees employees)
        {
            //   return Json(employees);
            if (employees != null)
            {
                // return Json(employees);
                await _unitOfWork.employeeRepo.Update(employees);
                _unitOfWork.save();
                TempData["successs"] = $"{employees.strFullName}'s info Updated successfully into the system";
            }
            else
            {
                TempData["Err"] = "Something went wrong";
            }
            return Redirect("~/Employees/Index");
        }




        [HttpPost]
        public async Task<IActionResult> RemoveEMployee(string id)
        {
            //   return Json(employees);
            if (id != null)
            {
                Employees e = await _unitOfWork.employeeRepo.GetById(id);
                if (e != null)
                {
                    e.strActive_Status = Active_Status.In_Active;
                    await _unitOfWork.employeeRepo.Update(e);
                    _unitOfWork.save();
                    TempData["Err"] = $"{e.strFullName} is now in Active";
                }
                else
                {
                    TempData["Err"] = "Something went wrong";
                }
            }
            else
            {
                TempData["Err"] = "Something went wrong";
            }
            return Redirect("~/Employees/Index");
        }



        [HttpPost]
        public async Task<IActionResult> RemoveOverTime(string id, string Employeename)
        {
            //   return Json(employees);
            if (id != null)
            {
                OverTime e = await _unitOfWork.overTimeRepo.GetById(id);
                if (e != null)
                {
                    await _unitOfWork.overTimeRepo.Remove(e);
                    _unitOfWork.save();
                    TempData["Err"] = $"Overtime amount of {e.strAmount} for {Employeename}  was Removed";
                }
                else
                {
                    TempData["Err"] = "Something went wrong";
                }
            }
            else
            {
                TempData["Err"] = "Something went wrong";
            }

            return Redirect("~/Employees/OverTime");
        }




        [HttpPost]
        public async Task<IActionResult> RemoveCommission(string id, string Employeename)
        {
            //   return Json(employees);
            if (id != null)
            {
                Commission e = await _unitOfWork.Icommissionrepo.GetById(id);
                if (e != null)
                {
                    await _unitOfWork.Icommissionrepo.Remove(e);
                    _unitOfWork.save();
                    TempData["Err"] = $"Commission amount of {e.strAmount} for {Employeename}  was Removed";
                }
                else
                {
                    TempData["Err"] = "Something went wrong";
                }
            }
            else
            {
                TempData["Err"] = "Something went wrong";
            }

            return Redirect("~/Employees/Commission");
        }


    }
}

Controllers/Job_GroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PAYROL_SYSTEM.Interfaces;
using PAYROL_SYSTEM.Models;

namespace PAYROL_SYSTEM.Controllers
{
    public class Job_GroupController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public Job_GroupController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {

            return View();
        }

        public async Task<IActionResult> CreateJobGroup(Job_Groups job_Groups)
        {
            job_Groups.strId = Guid.NewGuid().ToString();
            // return Json(job_Groups);
            if (!ModelState.IsValid)
            {
                // return Json(job_Groups);
                await _unitOfWork.jobGroupRepo.AddNew(job_Groups);
                _unitOfWork.save();

                TempData["successs"] = $"{job_Groups.strGroupName} was added successfully";
            }
            else
            {
                TempData["Err"] = "Something went wrong..";
            }
            return Redirect("~/Job_Group/Index");
        }

        public async Task<IActionResult> UpdateJobGroup(Job_Groups job_Groups)
        {
            if (ModelState.IsValid)
            {

                await _unitOfWork.jobGroupRepo.Update(job_Groups);
                _unitOfWork.save();

                TempData["successs"] = $"{job_Groups.strGroupName} Updated successfully";
            }
            else
            {
                TempData["Err"] = "Something went wrong..";
            }
            return Redirect("~/Job_Group/Index");
        }
        public async Task<IActionResult> RemoveJobGroup(string id)
        {
            Job_Groups j = await _unitOfWork.jobGroupRepo.GetById(id);

            if (j != null)
            {
                await _unitOfWork.jobGroupRepo.Remove(j);
                _unitOfWork.save();

                TempData["Err"] = $"{j.strGroupName} Removed successfully";
            }
            else
            {
                TempData["Err"] = "Something went wrong";
            }

            return Redirect("~/Job_Group/Index");
        }

    }
}

Controllers/PayslipsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PAYROL_SYSTEM.Interfaces;
using PAYROL_SYSTEM.Models;

namespace PAYROL_SYSTEM.Controllers
{
    public class PayslipsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public PayslipsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public async Task<IActionResult> UpdatepayeeInfo(double Payeeamount,string strId)
        {
            PayslipMonthlyInfo p = await _unitOfWork.payslipInfo.GetById(strId);
            if (p != null)
            {
                p.PAYE = Payeeamount;
               await  _unitOfWork.payslipInfo.Update(p);
                _unitOfWork.save();
                TempData["successs"] = "Payslip info updated Successfully";

            }
            else
            {
                TempData["Err"] = "Something went wrong";
            }
            return Redirect("~/Payslips/Index"); 
        }
        public IActionResult Index( string id)
        {
            ViewBag.payslipMonthlyInfos = id;

           

            return View();
        }
        public IActionResult GeneratePayslip(string id)
        {
            ViewBag.id = id;
            return View();
        }
    }
}

Views/Shared/_CheckboxList.cshtml
@model PAYROL_SYSTEM.Models.CheckedAllowanceType
@inject PAYROL_SYSTEM.Interfaces.IUnitOfWork _unitOfWork
@{
    int x = 0;
}
@foreach (var allowancetype in await _unitOfWork.allowanceTypeRepo.GetAll())
{
    <div>
        <input type="hidden" value="@allowancetype.strId" asp-for="checkedAllowances[x].strAllowancetypeId" />

        <div class="form-group form-check">
            <label class="form-check-label" style="color:black">
                <input class="form-check-input"  asp-for="checkedAllowances[x].strIsChecked" />
                @allowancetype.strAllowanceTypeName
            </label>
        </div>
    </div>
    x++;

}

Views/Shared/_DshboardsideMenu.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@using Newtonsoft.Json
@using PAYROL_SYSTEM.Session;

@{
    var CompanyId = PAYROL_SYSTEM.Controllers.HomeController.CompanyId;
    var image = HttpContextAccessor.HttpContext.Session.GetString("Imageurl");
    var name = HttpContextAccessor.HttpContext.Session.GetString("Name");
    var desc = HttpContextAccessor.HttpContext.Session.GetString("Desc");
    var Connected = HttpContextAccessor.HttpContext.Session.GetString("Connected");

    var strUserId = HttpContextAccessor.HttpContext.Session.GetString("strUserId");
}
<!-- Left side column. contains the logo and sidebar -->
@*<aside class="main-sidebar" style="background-color:white;color:black;">*@
<aside class="main-sidebar" style="background-color:#0C4A60;color:white;box-shadow: 1px 6px 22px 3px rgba(0,0,0,0.1);">

    <!-- sid;white-sbar: style can be found in sidebar.less -->
    <section class="sidebar" style="height: auto;">

        <ul class="sidebar-menu treeview" data-widget="tree">

            <li class="treeview" style="height: auto;color:black">
                <a asp-action="Dashboard" onclick="reload()" asp-controller="Home">
                    <i style="color:white" class="fal fa-tachometer-alt-slowest"></i>
                    <span style="color:white;margin-left:8px">
                        <b>Main Dashboard</b>

                    </span>
                </a>
                <script>
                    function reload() {

                        window.location = 'http://belgutdairy-001-site1.ctempurl.com/Home/Dashboard';
                        //window.location = 'https://localhost:44352/Home/Dashboard/';
                    }
                </script>


            </li>
            <style>
                .a:hover {
                    background-color: red;
                }
            </style>
            @if (CompanyId != null)
            {
                <li class="treeview" style="height: auto;color:white">
                    <a href="#" style="color:white">
                        <i class="fa fa-book" aria-hidden="true"></i>

                        <span style="color:white;" class="Mennnnu"> Employees  <br /><span style="margin-left:44px;font-size:x-small" class="Mennnnu">View/Manage Employees </span></span>
                        <span class="pull-right-container">
                            <i style="color:white" class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu" style="display: none">
                        <li>
                            <a asp-action="Index" asp-controller="Employees" asp-route-Id="@CompanyId">
                                <i class="fa fa-eye" aria-hidden="true"></i>View all Employees
                            </a>
                        </li>
                        <li>
                            <a asp-action="OverTime" asp-controller="Employees" asp-route-Id="@CompanyId">
                                <i class="fa fa-eye" aria-hidden="true"></i>Employee OverTime
                            </a>
                        </li>
                        <li>
                            <a asp-action="Commission" asp-controller="Employees" asp-route-Id="@CompanyId">
                                <i class="fa fa-eye" aria-hidden="true"></i>Employee Commission
                            </a>
                        </li>
                        <li>
                            <a asp-action="Index" asp-controller="Allowances" asp-route-Id="@CompanyId">
                                <i class="fa fa-eye" aria-hidden="true"></i>Employee Allowances
                            </a>
                        </li>
                        <li>
                            <a asp-action="Index" asp-controller="Payslips" asp-route-Id="@CompanyId">
                                <i class="fa fa-eye" aria-hidden="true"></i>Generate Payslips
                            </a>
                        </li>


                    </ul>
                </li>
            }
            <li class="treeview" style="height: auto;color:white">
                <a href="#" style="color:white">
                    <i class="fa fa-book" aria-hidden="true"></i>
                    <span style="color:white;" class="Mennnnu"> Departments  <br /><span style="margin-left:44px;font-size:x-small" class="Mennnnu">View/Manage departments </span></span>
                    <span class="pull-right-container">
                        <i style="color:white" class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu" style="display: none">
                    <li>
                        <a asp-action="Department" asp-controller="Home" asp-route-Id="">
                            <i class="fa fa-eye" aria-hidden="true"></i>View Departments
                        </a>
                    </li>


                </ul>
            </li>
            <li class="treeview" style="height: auto;color:white">
                <a href="#" style="color:white">
                    <i class="fa fa-book" aria-hidden="true"></i>
                    <span style="color:white;" class="Mennnnu"> Designation/Role  <br /><span style="margin-left:44px;font-size:x-small" class="Mennnnu">View/Manage Designation/Roles </span></span>
                    <span class="pull-right-container">
                        <i style="color:white" class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu" style="display: none">
                    <li>
                        <a asp-action="Index" asp-controller="DesignationRole" asp-route-Id="">
                            <i class="fa fa-eye" aria-hidden="true"></i>View Designation/Roles
                        </a>
                    </li>


                </ul>
            </li>
            @*<li class="treeview" style="height: auto;color:white">
            <a href="#" style="color:white">
                <i class="fa fa-book" aria-hidden="true"></i>
                <span style="color:white;" class="Mennnnu"> Job Groups  <br /><span style="margin-left:44px;font-size:x-small" class="Mennnnu">View/Manage Job Groups </span></span>
                <span class="pull-right-container">
                    <i style="color:white" class="fa fa-angle-left pull-right"></i>
                </span>
            </a>
            <ul class="treeview-menu" style="display: none">
                <li>
                    <a asp-action="Index" asp-controller="Job_Group" asp-route-Id="">
                        <i class="fa fa-eye" aria-hidden="true"></i>View Job Groups
                    </a>
                </li>


            </ul>
        </li>*@
            <li class="treeview" style="height: auto;color:white">
                <a href="#" style="color:white">
                    <i class="fa fa-book" aria-hidden="true"></i>
                    <span style="color:white;" class="Mennnnu"> Allowance Types  <br /><span style="margin-left:44px;font-size:x-small" class="Mennnnu">View/Manage Allowance Types </span></span>
                    <span class="pull-right-container">
                        <i style="color:white" class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu" style="display: none">
                    <li>
                        <a asp-action="Index" asp-controller="AllowanceTypes" asp-route-Id="">
                            <i class="fa fa-eye" aria-hidden="true"></i>View Allowance Types
                        </a>
                    </li>


                </ul>
            </li>

        </ul>
    </section>
    <!-- /.sidebar -->
</aside>

<script src="~/dist/js/adminlte.min.js"></script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <script>
        // Disable right-click
        document.addEventListener('contextmenu', (e) => e.preventDefault());

        function ctrlShiftKey(e, keyCode) {
            return e.ctrlKey && e.shiftKey && e.keyCode === keyCode.charCodeAt(0);
        }

        document.onkeydown = (e) => {
            // Disable F12, Ctrl + Shift + I, Ctrl + Shift + J, Ctrl + U
            if (
                event.keyCode === 123 ||
                ctrlShiftKey(e, 'I') ||
                ctrlShiftKey(e, 'J') ||
                ctrlShiftKey(e, 'C') ||
                (e.ctrlKey && e.keyCode === 'U'.charCodeAt(0))
            )
                return false;
        };
    </script>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>PAYROL</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body oncontextmenu="return false;">
    @*<header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AIR_BNB</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>*@
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2023 - AIR_BNB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>*@

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_Search.cshtml
<div style="padding:8px;margin:8px">
    <input class="form-control border-0" id="myInput" onkeyup="myFunction()" style="background-color:#b2bbc4;color:black;border-radius:30px;font-family:'Century Gothic'" required placeholder="Search" />

</div>

<script>
    function myFunction() {
        var input, filter, ul, li, a, i, txtValue;
        input = document.getElementById("myInput");
        filter = input.value.toUpperCase();
        ul = document.getElementById("myUL");
        li = ul.getElementsByTagName("tr");
        for (i = 0; i < li.length; i++) {
            a = li[i].getElementsByTagName("b")[0];

            txtValue = a.textContent || a.innerText;
            if (txtValue.toUpperCase().indexOf(filter) > -1) {
                li[i].style.display = "";
            } else {
                li[i].style.display = "none";
            }
        }
    }

</script>